"""
Iteration 2 regression tests - new features:
- Line detail exposes nationalMinutes / smsUsed / cdrs.calledNumber
- /api/me/summary lines include nationalMinutes / smsUsed
- Invoices have period/dueDate/customerAddress/paymentMethod/consumption
- PDF generated with Goroky layout
- POST /api/customers accepts iban/paymentMethod; POST /api/orders reflects them
"""
import os
import uuid
import requests
import pytest

BASE_URL = os.environ.get("REACT_APP_BACKEND_URL", "https://likes-telecom-app.preview.emergentagent.com").rstrip("/")
ADMIN_EMAIL = "admin@goroky.com"
ADMIN_PASS = "Goroky2026!"
CLIENT_EMAIL = "cliente@goroky.com"
CLIENT_PASS = "Cliente2026!"


def _login(email, pw):
    r = requests.post(f"{BASE_URL}/api/auth/login", json={"email": email, "password": pw}, timeout=20)
    assert r.status_code == 200, f"login failed {email}: {r.status_code} {r.text}"
    return r.json()["token"]


@pytest.fixture(scope="module")
def admin_token():
    return _login(ADMIN_EMAIL, ADMIN_PASS)


@pytest.fixture(scope="module")
def client_token():
    return _login(CLIENT_EMAIL, CLIENT_PASS)


def _h(t):
    return {"Authorization": f"Bearer {t}"}


# ---------- LINE DETAIL: nationalMinutes / smsUsed / cdrs ----------
class TestLineDetailUsage:
    def test_mobile_line_has_usage_fields(self, admin_token):
        # find a Mobile ACTIVE line
        lines = requests.get(f"{BASE_URL}/api/lines", headers=_h(admin_token), timeout=20).json()
        mobile = next((l for l in lines if l.get("family") == "Mobile"), None)
        assert mobile is not None, "no mobile line in seeded data"
        r = requests.get(f"{BASE_URL}/api/lines/{mobile['lineNumber']}", headers=_h(admin_token), timeout=20)
        assert r.status_code == 200, r.text
        d = r.json()
        for k in ["nationalMinutes", "smsUsed", "usedGB", "totalGB", "cdrs"]:
            assert k in d, f"missing field {k} in line detail"
        assert isinstance(d["nationalMinutes"], int)
        assert isinstance(d["smsUsed"], int)
        assert isinstance(d["cdrs"], list)
        assert len(d["cdrs"]) > 0, "expected cdrs generated by seed"

    def test_cdrs_contain_voice_sms_data_and_calledNumber(self, admin_token):
        lines = requests.get(f"{BASE_URL}/api/lines", headers=_h(admin_token), timeout=20).json()
        mobile = next((l for l in lines if l.get("family") == "Mobile"), None)
        d = requests.get(f"{BASE_URL}/api/lines/{mobile['lineNumber']}", headers=_h(admin_token), timeout=20).json()
        cdrs = d["cdrs"]
        types = {c.get("type") for c in cdrs}
        # At least VOICE should be present (main check); SMS/DATA may vary due to random.
        assert "VOICE" in types, f"expected VOICE cdr, got {types}"
        # every VOICE cdr has calledNumber, date and duration
        for c in cdrs:
            assert "date" in c and c["date"]
            assert "duration" in c
            if c["type"] in ("VOICE", "SMS"):
                assert c.get("calledNumber"), f"VOICE/SMS cdr missing calledNumber: {c}"


# ---------- ME SUMMARY (client) ----------
class TestMeSummaryUsage:
    def test_lines_have_usage(self, client_token):
        r = requests.get(f"{BASE_URL}/api/me/summary", headers=_h(client_token), timeout=20)
        assert r.status_code == 200
        d = r.json()
        assert len(d["lines"]) >= 1
        mob = [l for l in d["lines"] if l.get("family") == "Mobile"]
        assert mob, "client should have at least 1 mobile line"
        for l in mob:
            assert "nationalMinutes" in l, f"missing nationalMinutes: {l.keys()}"
            assert "smsUsed" in l, f"missing smsUsed: {l.keys()}"
            assert isinstance(l["nationalMinutes"], int)
            assert isinstance(l["smsUsed"], int)


# ---------- INVOICE FIELDS + PDF ----------
class TestInvoiceGorokyFormat:
    def test_invoice_has_new_fields(self, admin_token):
        invs = requests.get(f"{BASE_URL}/api/invoices", headers=_h(admin_token), timeout=20).json()
        assert invs, "expected seeded invoices"
        inv = invs[0]
        for k in ["period", "dueDate", "customerAddress", "paymentMethod", "consumption"]:
            assert k in inv, f"invoice missing {k}: keys={list(inv.keys())}"
        assert isinstance(inv["consumption"], list)

    def test_pdf_is_valid_goroky(self, admin_token):
        invs = requests.get(f"{BASE_URL}/api/invoices", headers=_h(admin_token), timeout=20).json()
        inv = invs[0]
        r = requests.get(f"{BASE_URL}/api/invoices/{inv['id']}/pdf", headers=_h(admin_token), timeout=30)
        assert r.status_code == 200
        assert r.headers.get("content-type", "").startswith("application/pdf")
        assert r.content[:4] == b"%PDF"
        # at least 2 pages -> reasonable size
        assert len(r.content) > 2000, f"pdf suspiciously small: {len(r.content)}"

    def test_pdf_client_own(self, client_token):
        invs = requests.get(f"{BASE_URL}/api/invoices", headers=_h(client_token), timeout=20).json()
        assert invs
        inv = invs[0]
        r = requests.get(f"{BASE_URL}/api/invoices/{inv['id']}/pdf", headers=_h(client_token), timeout=30)
        assert r.status_code == 200
        assert r.content[:4] == b"%PDF"


# ---------- CUSTOMER iban/paymentMethod + ORDER carries paymentMethod ----------
class TestCustomerPaymentAndOrderPropagation:
    def test_create_customer_with_iban_and_payment(self, admin_token):
        unique_id = f"T{uuid.uuid4().hex[:8].upper()}"
        payload = {
            "fiscalId": unique_id,
            "customerType": "Residential",
            "name": "TEST_IbanCli",
            "firstSurname": "Prueba",
            "email": f"test_{unique_id.lower()}@qa.com",
            "contactPhone": "600000000",
            "iban": "ES9121000418450200051332",
            "paymentMethod": "SEPA CORE",
            "street": "Calle Test",
            "streetNumber": "5",
            "postalCode": "28080",
            "cityName": "Madrid",
            "provinceName": "Madrid",
        }
        r = requests.post(f"{BASE_URL}/api/customers", headers=_h(admin_token), json=payload, timeout=20)
        assert r.status_code == 200, r.text
        c = r.json()
        assert c["iban"] == payload["iban"]
        assert c["paymentMethod"] == "SEPA CORE"

        # persistence check via GET
        r2 = requests.get(f"{BASE_URL}/api/customers/{unique_id}", headers=_h(admin_token), timeout=20)
        assert r2.status_code == 200
        cust = r2.json()["customer"]
        assert cust["iban"] == payload["iban"]
        assert cust["paymentMethod"] == "SEPA CORE"

        # place order for this customer
        prods = requests.get(f"{BASE_URL}/api/products?family=Mobile", headers=_h(admin_token), timeout=20).json()
        pid = prods[0]["productId"]
        ro = requests.post(f"{BASE_URL}/api/orders", headers=_h(admin_token),
                           json={"fiscalId": unique_id, "productId": pid}, timeout=20)
        assert ro.status_code == 200, ro.text
        inv_id = ro.json()["invoiceId"]

        # verify invoice reflects paymentMethod + consumption listing includes the new mobile line
        invs = requests.get(f"{BASE_URL}/api/invoices?fiscalId={unique_id}",
                            headers=_h(admin_token), timeout=20).json()
        assert invs, "expected invoice after order"
        inv = next(i for i in invs if i["id"] == inv_id)
        assert inv["paymentMethod"] == "SEPA CORE"
        assert isinstance(inv["consumption"], list)
        # Consumption must contain the newly created mobile line
        line_numbers = [c.get("lineNumber") for c in inv["consumption"]]
        assert len(line_numbers) >= 1, f"expected mobile line in consumption, got {inv['consumption']}"

        # PDF valid too
        pdf = requests.get(f"{BASE_URL}/api/invoices/{inv_id}/pdf", headers=_h(admin_token), timeout=30)
        assert pdf.status_code == 200
        assert pdf.content[:4] == b"%PDF"
